name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "quilt-2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7d22d07027e8ef7cd55e3acd55bfa70694cfac9c771aabb1dc3e46b11245ad4"

[versions]
minecraft = "1.21"
quilt = "0.26.1-beta.1"
