name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "quilt-2.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a1a953b137b6396f0906539f82a9463d554a1b4455d80f9a1766cfa53207554"

[versions]
minecraft = "1.21"
quilt = "0.26.4-beta.1"
