name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc2976ed1049d8530a531dbd10fe4b4652bb945ab1b5caf0216753087b5f1c44"

[versions]
minecraft = "1.21"
quilt = "0.26.1-beta.1"
