name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "922af0df5177d9c6bcf78ed3c6551a643b78af0a7290ac9de911519956c7f169"

[versions]
minecraft = "1.21"
quilt = "0.26.1-beta.1"
