name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.0.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02a258ee4af59ef06b4a7a574fdc635423e4c6c221dd781f60365467c9262b7c"

[versions]
minecraft = "1.21"
quilt = "0.26.1-beta.1"
