name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "quilt-2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "248cc5a78e4e4fea4408faef297ff92867d00a1fe8877285ad3d2804bce59343"

[versions]
minecraft = "1.21"
quilt = "0.26.4-beta.1"
